export interface Bird {
    "Species number": number;
    Name: string;
    "Latin name": string;
    "Alt names/ mispellings"?: string;
    "Sex/ Age Variations"?: string;
    "Seasonal Variations"?: string | null;
    "Conservation status": string;
    Group: string;
    "Time of year active (UK)": string;
    Summary?: string;
    "Picture (Primary)"?: string;
    "Picture 2"?: string;
    "Picture 3"?: string;
    "Picture 4"?: string;
    Illustration?: string;
    Audio?: string;
    "Distribution map"?: string;
    "Plumage colour(s)"?: string;
    "Beak Colour(s)"?: string;
    "Feet colour(s)"?: string;
    "Leg colour(s)"?: string;
    "Beak Shape 1"?: string;
    "Beak shape 2 (optional)"?: string | null;
    "Tail shape 1"?: string;
    "Tail shape 2 (optional)"?: string | null;
    "Pattern/ Markings"?: string;
    Diet?: string;
    "Population (UK)"?: string;
    "Min Length (cm)"?: number;
    "Max Length (cm)"?: number;
    "Mean length (cm)"?: number;
    Size?: string;
    "Wingspan (cm)"?: string;
    "Weight (g)"?: string;
    "Habitat(s)"?: string;
    Appearance?: string;
    Habitat?: string;
    Call?: string;
    Behaviour?: string;
    "Fact 1"?: string;
    "Fact 2"?: string;
    "Fact 3"?: string;
    "Similar species"?: string;
    "Where to see them (countries)"?: string;
  }
  