# Column structure extracted from Excel file

columns = {
    'Key Species Information': [
        'Species number',
        'Name',
        'Latin name',
        'Alt names/ mispellings',
        'Sex/ Age Variations',
        'Seasonal Variations',
        'Conservation status',
        'Group',
        'Time of year active (UK)',
        'Summary (200 characters)',
    ],
    'Media': [
        'Picture (Primary)',
        'Picture 2',
        'Picture 3',
        'Picture 4',
        'Illustration',
        'Audio',
        'Distribution map',
    ],
    'Key features': [
        'Plumage colour(s)',
        'Beak Colour(s)',
        'Feet colour(s)',
        'Leg colour(s)',
        'Beak Shape 1',
        'Beak shape 2 (optional)',
        'Tail shape 1',
        'Tail shape 2 (optional)',
        'Pattern/ Markings',
        'Diet',
        'Population (UK)',
        'Min Length (cm)',
        'Max Length (cm)',
        'Mean length (cm)',
        'Size',
        'Wingspan (cm)',
        'Weight (g)',
        'Habitat(s)',
    ],
    'How to identify': [
        'Appearance',
        'Size',
        'Habitat',
        'Call',
        'Behaviour',
    ],
    'Trivia': [
        'Fact 1',
        'Fact 2',
        'Fact 3',
    ],
    'Other': [
        'Similar species',
        'Where to see them (countries)',
    ],
}
